
version: "3"
tasks:
  
  gplagin:
    aliases:
      - gen
    desc: "Generate protobuf code"
    cmds:
      - protoc -I ./culc/ ./culc/culc.proto  --go_out=./gen/go --go_opt=paths=source_relative  --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative  --grpc-gateway_out=./gen/go --grpc-gateway_opt=paths=source_relative --grpc-gateway_opt generate_unbound_methods=true 

